### PR TITLE
24 add plotting functions for the calibration plots and changed the plot function 

### PR DESCRIPTION
**Pull request by Rockdeldiablo**
@pat-alt  @MojiFarmanbar  the pull requests are becoming interlinked, especially this one and the 90-average-calibration in laplaceredux.
if this one is not merged then plot doesn't work and if the 90 isn't merged this pull request  risks to break the behaviour of plot(la,....).
how do we proceed?  should  I split out the change in glm_predictive distribution from the other branch and make a pull request only for that? i think it's the best option

### CODE REVIEW

**Review by pat-alt — CHANGES_REQUESTED** [review]
Update LaplaceRedux dependency and run checks.

**Comment by Rockdeldiablo** [comment]
@pat-alt  no , the test seems to fail because of this function

`"""
    (la::AbstractLaplace)(X::AbstractArray)

Calling a model with Laplace Approximation on an array of inputs is equivalent to explicitly calling the `predict` function.
"""
function (la::AbstractLaplace)(X::AbstractArray)
    return la.model(X)
end`  the error reported is  Multi-class: Error During Test at C:\Users\Pasqu\Documents\julia_projects\TaijaPlotting.jl\test\LaplaceRedux.jl:55
  Got exception outside of a @test
  MethodError: no method matching (::Laplace)(::Vector{Float32}; link_approx::Symbol)

  Closest candidates are:
    (::LaplaceRedux.AbstractLaplace)(::AbstractArray) got unsupported keyword argument "link_approx"
     @ LaplaceRedux C:\Users\Pasqu\.julia\packages\LaplaceRedux\YqyQs\src\baselaplace\predicting.jl:197

**Comment by Rockdeldiablo** [comment]
@pat-alt  ok i think the problem is in line 91 of the plot function

**Comment by Rockdeldiablo** [comment]
@pat-alt  seems like some weird side effect appears in `TaijaData.load_blobs(centers = nout)` for the older versions of julia.

**Comment by pat-alt** [comment]
@Rockdeldiablo yeh what happened here is that on legacy versions LaplaceRedux is downgraded to `v0.2`. I've now removed legacy versions from compat and tests, since `v1.10` is the new LTS anyway and this package will in any case need to undergo some significant changes in the future.

**Review by pat-alt — APPROVED** [review]

**Comment by pat-alt** [comment]
Happy to merge @Rockdeldiablo

**Pull request merged**
